### ISSUE TITLE
RIMBAnet Parallel on SLURM system and minimum sample size

### ISSUE THREAD

**Issue by harrsha4** [mw201608/BayesianNetwork#1]
Hello, 

I am an undergraduate researcher and I have been using RIMBAnet for the past several months. One issue that I have to deal with every time I run the program is the amount of time it takes due to iterating over a 1000 networks. I did not know that it could be run parallel on a cluster until I came across this github page. The issue is that my institution cluster system uses SLURM as opposed to LSF; would I be able to create SLURM scripts that mirror the LSF scripts for parallel jobs. 

Secondly, I am working with 2 datasets for which I am applying RIMBAnet. One dataset has a sample size of 129, which is within the tested range from the original RIMBAnet paper, but the other dataset has a sample size of only 67. Would it still be okay to run RIMBAnet on the smaller dataset.

**Comment by mw201608** [comment]
Hi,

It should be straightforward to prepare SLURM scripts based on the current LSF scripts.  I don't have SLURM environment so am unable to provide such scripts.

I think sample size 129 is already very small. A sample size of 67 is definitely too small to run RIMBANet.

**Comment by harrsha4** [comment]
Thank you for the prompt response. Am I correct in assuming that 67 is a low sample size even when you have priors (cis-eqtls). Also, I see that discretized data is the only input needed for this run. Is continuous data no longer needed?
